config/routes.rb
Rails.application.routes.draw do
  resource :wizard do
    get :step1
    get :step2
    get :step3
    get :step4

    post :validate_step
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, format: { with: /@/ }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address_1, presence: true
  validates :zip_code, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  before_action :load_user_wizard, except: %i(validate_step)

  def validate_step
    current_step = params[:current_step]

    @user_wizard = wizard_user_for_step(current_step)
    @user_wizard.user.attributes = user_wizard_params
    session[:user_attributes] = @user_wizard.user.attributes

    if @user_wizard.valid?
      next_step = wizard_user_next_step(current_step)
      create and return unless next_step

      redirect_to action: next_step
    else
      render current_step
    end
  end

  def create
    if @user_wizard.user.save
      session[:user_attributes] = nil
      redirect_to root_path, notice: 'User succesfully created!'
    else
      redirect_to({ action: Wizard::User::STEPS.first }, alert: 'There were a problem when creating the user.')
    end
  end

  private

  def load_user_wizard
    @user_wizard = wizard_user_for_step(action_name)
  end

  def wizard_user_next_step(step)
    Wizard::User::STEPS[Wizard::User::STEPS.index(step) + 1]
  end

  def wizard_user_for_step(step)
    raise InvalidStep unless step.in?(Wizard::User::STEPS)

    "Wizard::User::#{step.camelize}".constantize.new(session[:user_attributes])
  end

  def user_wizard_params
    params.require(:user_wizard).permit(:email, :first_name, :last_name, :address_1, :address_2, :zip_code, :city, :country, :phone_number)
  end

  class InvalidStep < StandardError; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h2>STEPFORM</h2>

<%= link_to "Create a user", step1_wizard_path, class: 'btn btn-success' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>STEPFORM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:alert] %><div class="alert alert-danger"><%= flash[:alert] %></div><% end %>
      <% if flash[:notice] %><div class="alert alert-success"><%= flash[:notice] %></div><% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/wizards/step1.html.erb
<ol class="breadcrumb">
  <li class='active'>Step 1</li>
  <li>Step 2</li>
  <li>Step 3</li>
  <li>Step 4</li>
</ol>

<%= simple_form_for @user_wizard, as: :user_wizard, url: validate_step_wizard_path do |f| %>
  <%= f.error_notification %>

  <%= hidden_field_tag :current_step, 'step1' %>
  <%= f.input :email %>

  <%= f.submit 'Continue' %>
<% end %>

app/views/wizards/step2.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Step 1", step1_wizard_path %></li>
  <li class="active">Step 2</li>
  <li>Step 3</li>
  <li>Step 4</li>
</ol>

<%= simple_form_for @user_wizard, as: :user_wizard, url: validate_step_wizard_path do |f| %>
  <%= f.error_notification %>

  <%= hidden_field_tag :current_step, 'step2' %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>

  <%= f.submit 'Continue' %>
<% end %>

app/views/wizards/step3.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Step 1", step1_wizard_path %></li>
  <li><%= link_to "Step 2", step2_wizard_path %></li>
  <li class="active">Step 3</li>
  <li>Step 4</li>
</ol>

<%= simple_form_for @user_wizard, as: :user_wizard, url: validate_step_wizard_path do |f| %>
  <%= f.error_notification %>

  <%= hidden_field_tag :current_step, 'step3' %>
  <%= f.input :address_1 %>
  <%= f.input :address_2 %>
  <%= f.input :zip_code %>
  <%= f.input :city %>
  <%= f.input :country %>

  <%= f.submit 'Continue' %>
<% end %>

app/views/wizards/step4.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Step 1", step1_wizard_path %></li>
  <li><%= link_to "Step 2", step2_wizard_path %></li>
  <li><%= link_to "Step 3", step3_wizard_path %></li>
  <li class="active">Step 4</li>
</ol>

<%= simple_form_for @user_wizard, as: :user_wizard, url: validate_step_wizard_path do |f| %>
  <%= f.error_notification %>

  <%= hidden_field_tag :current_step, 'step4' %>
  <%= f.input :phone_number %>

  <%= f.submit 'Finish' %>
<% end %>